# Generated by Django 2.0.2 on 2018-02-21 17:40

from django.db import migrations, models
import django.db.models.deletion
import randomizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Game', max_length=50)),
                ('logo', models.ImageField(upload_to=randomizer.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='GameByPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Roger', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='gamebyplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='speed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.Speed'),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.Time'),
        ),
    ]
